package com.lumyrinth.app.ui

import android.os.SystemClock
import androidx.compose.foundation.Canvas
import androidx.compose.animation.AnimatedContent
import androidx.compose.animation.core.*
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.animation.slideInHorizontally
import androidx.compose.animation.slideOutHorizontally
import androidx.compose.animation.togetherWith
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.lumyrinth.app.domain.*
import com.lumyrinth.app.data.UserPreferencesRepository
import com.lumyrinth.app.data.session.CustomRhythmEntity
import com.lumyrinth.app.data.session.SessionEntity
import com.lumyrinth.app.data.session.SessionRepository
import com.lumyrinth.app.haptics.HapticGuide
import com.lumyrinth.app.audio.GuidanceSoundController
import com.lumyrinth.app.audio.AmbientAudioController
import com.lumyrinth.app.ui.theme.LumyrinthColor
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlin.math.min

private enum class Screen { HOME, EXPLORE, PROGRESS, SETTINGS, DETAIL, COUNTDOWN, SESSION, COMPLETE, CUSTOM }

@Composable fun LumyrinthApp() {
    val context = LocalContext.current
    val preferencesRepository = remember { UserPreferencesRepository(context) }
    val preferences by preferencesRepository.preferences.collectAsState(initial = null)
    val scope = rememberCoroutineScope()
    val sessionRepository = remember { SessionRepository.from(context) }
    val savedSessions by sessionRepository.sessions.collectAsState(initial = emptyList())
    val savedRhythms by sessionRepository.customRhythms.collectAsState(initial = emptyList())
    var screen by remember { mutableStateOf(Screen.HOME) }
    var exercise by remember { mutableStateOf(PresetExercises.all.first()) }
    var minutes by remember { mutableStateOf(3) }
    fun open(e: BreathingExercise) { exercise = e; minutes = e.defaultMinutes; screen = Screen.DETAIL }
    if (preferences == null) return Box(Modifier.fillMaxSize().background(LumyrinthColor.Background))
    if (!preferences!!.onboardingComplete) {
        Onboarding(
            complete = { scope.launch { preferencesRepository.completeOnboarding() } },
            firstSession = { scope.launch { preferencesRepository.completeOnboarding() }; open(PresetExercises.all.last()); minutes = 1 },
        )
        return
    }
    Box(Modifier.fillMaxSize().background(LumyrinthColor.Background)) {
        AnimatedContent(screen, transitionSpec = { (fadeIn(animationSpec = tween(260)) + slideInHorizontally(animationSpec = tween(260)) { it / 12 }) togetherWith (fadeOut(animationSpec = tween(180)) + slideOutHorizontally(animationSpec = tween(180)) { -it / 18 }) }, label = "lumyrinth_screen") { active -> when (active) {
            Screen.HOME -> Home { open(it) }
            Screen.EXPLORE -> Explore({ open(it) }, { screen = Screen.CUSTOM }, savedRhythms.map { BreathingExercise(it.id,it.name,ExerciseCategory.CUSTOM,"Your personal breathing rhythm.",BreathingPattern(it.inhaleSeconds,it.holdAfterInhaleSeconds,it.exhaleSeconds,it.holdAfterExhaleSeconds),3) })
            Screen.PROGRESS -> Progress(savedSessions)
            Screen.SETTINGS -> Settings()
            Screen.DETAIL -> Detail(exercise, minutes, { minutes = it }, { screen = Screen.COUNTDOWN }, { screen = Screen.EXPLORE })
            Screen.COUNTDOWN -> Countdown(exercise) { screen = Screen.SESSION }
            Screen.SESSION -> Session(exercise, minutes, { actual, cycles -> scope.launch { sessionRepository.save(SessionEntity(exerciseId=exercise.id,exerciseName=exercise.name,startedAtEpochMillis=System.currentTimeMillis()-actual,completedAtEpochMillis=System.currentTimeMillis(),targetDurationMillis=minutes*60_000L,actualDurationMillis=actual,cyclesCompleted=cycles,completed=true)) }; screen = Screen.COMPLETE }, { screen = Screen.DETAIL })
            Screen.COMPLETE -> Complete(exercise, minutes, { screen = Screen.HOME }, { screen = Screen.SESSION })
            Screen.CUSTOM -> CustomRhythmScreen({ custom -> scope.launch { sessionRepository.saveCustomRhythm(CustomRhythmEntity(custom.id,custom.name,custom.pattern.inhaleSeconds,custom.pattern.holdAfterInhaleSeconds,custom.pattern.exhaleSeconds,custom.pattern.holdAfterExhaleSeconds,System.currentTimeMillis())) }; exercise = custom; minutes = 3; screen = Screen.DETAIL }, { screen = Screen.EXPLORE })
        } }
        if (screen in listOf(Screen.HOME, Screen.EXPLORE, Screen.PROGRESS, Screen.SETTINGS)) Bottom(screen) { screen = it }
    }
}
@Composable private fun Page(content: @Composable () -> Unit) = Box(Modifier.fillMaxSize().padding(20.dp, 28.dp, 20.dp, 86.dp)) { content() }
@Composable private fun Onboarding(complete: () -> Unit, firstSession: () -> Unit) { var step by remember { mutableStateOf(0) }; var goals by remember { mutableStateOf(setOf("Relax")) }; Box(Modifier.fillMaxSize().background(LumyrinthColor.Background).padding(28.dp)) { Column(Modifier.fillMaxSize(),verticalArrangement=Arrangement.Center,horizontalAlignment=Alignment.CenterHorizontally) { Text("LUMYRINTH",color=LumyrinthColor.VioletBright,fontSize=13.sp,fontWeight=FontWeight.SemiBold); Spacer(Modifier.height(18.dp)); when(step) { 0 -> { Text("Find your rhythm.",color=LumyrinthColor.TextPrimary,fontSize=42.sp,textAlign=TextAlign.Center); Spacer(Modifier.height(12.dp)); Text("A private space for calm, guided breathing.",color=LumyrinthColor.TextSecondary,textAlign=TextAlign.Center) }; 1 -> { Text("What are you looking for?",color=LumyrinthColor.TextPrimary,fontSize=30.sp,textAlign=TextAlign.Center); Spacer(Modifier.height(18.dp)); listOf("Relax","Focus","Unwind","Sleep","A quick break","Build a habit").forEach { goal -> Chip(goal,goal in goals) { goals=if(goal in goals) goals-goal else goals+goal }; Spacer(Modifier.height(8.dp)) } }; 2 -> { Text("Guidance, your way.",color=LumyrinthColor.TextPrimary,fontSize=30.sp,textAlign=TextAlign.Center); Spacer(Modifier.height(12.dp)); Text("You can change these at any time.",color=LumyrinthColor.TextSecondary); Spacer(Modifier.height(22.dp)); CardRow("Haptic guidance","Soft cues at each phase","On") {}; Spacer(Modifier.height(8.dp)); CardRow("Sound guidance","Quiet tones, never spoken commands","On") {} }; else -> { Text("Begin gently.",color=LumyrinthColor.TextPrimary,fontSize=30.sp,textAlign=TextAlign.Center); Spacer(Modifier.height(12.dp)); Text("Breathe comfortably and naturally. Stop if you feel uncomfortable or dizzy.",color=LumyrinthColor.TextSecondary,textAlign=TextAlign.Center); Spacer(Modifier.height(24.dp)); Core(.45f,BreathPhase.INHALE,180.dp) } }; Spacer(Modifier.height(42.dp)); if(step<3) Primary("Continue") { if(step==1&&goals.isEmpty()) goals=setOf("Relax") else step++ } else { Primary("Begin 1-minute session",firstSession); Spacer(Modifier.height(10.dp)); OutlinedButton(complete,Modifier.fillMaxWidth()){Text("Explore first",color=LumyrinthColor.VioletBright)} } } } }
@Composable private fun Home(open: (BreathingExercise) -> Unit) = Page { LazyColumn(verticalArrangement = Arrangement.spacedBy(16.dp)) {
    item { Text("Good evening", color=LumyrinthColor.TextSecondary); Text("Find your rhythm.", color=LumyrinthColor.TextPrimary, fontSize=32.sp) }
    item { Hero { open(PresetExercises.all.first()) } }
    item { Label("How do you want to feel?") }
    item { Row(horizontalArrangement=Arrangement.spacedBy(8.dp)) { listOf("Calm" to 0,"Focused" to 1,"Rested" to 4).forEach { (t,i)-> Chip(t) { open(PresetExercises.all[i]) } } } }
    item { Label("Continue your rhythm") }; item { CardRow("Nightfall","5 min · Last practiced yesterday","Repeat") { open(PresetExercises.all[4]) } }
    item { Label("Today's progress") }; item { Row(horizontalArrangement=Arrangement.spacedBy(8.dp)) { Stat("2","sessions"); Stat("8","mindful min"); Stat("3","day rhythm") } }
} }
@Composable private fun Explore(open: (BreathingExercise) -> Unit, create: () -> Unit, custom: List<BreathingExercise>) = Page { var filter by remember { mutableStateOf<ExerciseCategory?>(null) }; LazyColumn(verticalArrangement=Arrangement.spacedBy(12.dp)) {
    item { Text("Explore",color=LumyrinthColor.TextPrimary,fontSize=32.sp); Text("Breathing practices for this moment.",color=LumyrinthColor.TextSecondary) }
    item { Row(horizontalArrangement=Arrangement.spacedBy(7.dp)) { listOf("All" to null,"Relax" to ExerciseCategory.RELAX,"Focus" to ExerciseCategory.FOCUS,"Sleep" to ExerciseCategory.SLEEP).forEach { (t,c)-> Chip(t,filter==c) { filter=c } } } }
    items(PresetExercises.all.filter { filter==null || it.category==filter }) { CardRow(it.name,it.description,"${it.defaultMinutes} min") { open(it) } }
    item { CardRow("My Rhythms","Create a rhythm that feels right for you.","Create", create) }
    items(custom) { CardRow(it.name,"Your saved rhythm","3 min") { open(it) } }
} }
@Composable private fun Progress(sessions: List<SessionEntity>) = Page { val summary=progressSummary(sessions); LazyColumn(verticalArrangement=Arrangement.spacedBy(14.dp)) { item { Text("Your Rhythm",color=LumyrinthColor.TextPrimary,fontSize=32.sp) }; item { Card(colors=CardDefaults.cardColors(containerColor=LumyrinthColor.SurfaceHigh),shape=RoundedCornerShape(24.dp)) { Column(Modifier.padding(22.dp)) { Text("Current rhythm",color=LumyrinthColor.TextSecondary); Text("${summary.currentRhythmDays} days",color=LumyrinthColor.VioletBright,fontSize=36.sp); Text("Best: ${summary.bestRhythmDays} days · ${summary.todayMinutes} mindful min today",color=LumyrinthColor.TextSecondary) } } }; item { Label("History") }; if(sessions.isEmpty()) item { Text("Your completed sessions will appear here.",color=LumyrinthColor.TextSecondary) } else items(sessions) { s->CardRow(s.exerciseName,"${if(s.completed)"Completed" else "Ended early"} · ${s.actualDurationMillis/60_000} min","${s.cyclesCompleted} cycles"){} } } }
@Composable private fun Settings() { val context=LocalContext.current; val repo=remember{UserPreferencesRepository(context)}; val prefs by repo.preferences.collectAsState(initial=null); val scope=rememberCoroutineScope(); Page { LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)) { item { Text("Settings",color=LumyrinthColor.TextPrimary,fontSize=32.sp); Text("Quietly yours.",color=LumyrinthColor.TextSecondary); Spacer(Modifier.height(12.dp)) }; item { SettingToggle("Haptic guidance","Soft cues at each breath phase",prefs?.hapticsEnabled?:true){scope.launch{repo.setHaptics(it)}} }; item { SettingToggle("Sound guidance","Gentle tonal guidance",prefs?.guidanceSoundsEnabled?:true){scope.launch{repo.setGuidanceSounds(it)}} }; item { SettingToggle("Keep screen awake","Only while a session is open",prefs?.keepScreenAwake?:true){scope.launch{repo.setKeepScreenAwake(it)}} }; item { Label("Ambient sound") }; items(listOf("None","Rain","Night","Ocean","Forest","Fireplace","Stream","Deep Space").chunked(3)) { row -> Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){row.forEach { sound->Chip(sound,prefs?.ambientSound==sound){scope.launch{repo.setAmbientSound(sound)}}} } }; item { Spacer(Modifier.height(12.dp)); Label("Your practice") }; item { CardRow("Reminders","A gentle daily invitation","Set up"){} }; item { CardRow("Data","Your practice stays on this device","Private"){} }; item { CardRow("About Lumyrinth","General wellness, not a medical device","View"){} } } } }
@Composable private fun Detail(e: BreathingExercise, mins:Int, set:(Int)->Unit, begin:()->Unit, back:()->Unit) = Page { Column(Modifier.fillMaxSize(),verticalArrangement=Arrangement.spacedBy(18.dp)) { Text("‹",color=LumyrinthColor.TextPrimary,fontSize=34.sp,modifier=Modifier.clickable { back() }); Text(e.name,color=LumyrinthColor.TextPrimary,fontSize=32.sp); Text(e.description,color=LumyrinthColor.TextSecondary,fontSize=16.sp); Core(.6f,BreathPhase.INHALE,190.dp); Label("Your rhythm"); Row(horizontalArrangement=Arrangement.spacedBy(8.dp)) { e.pattern.phases().forEach { (p,s)-> Chip("${p.label} ${s}s") {} } }; Label("Duration"); Row(horizontalArrangement=Arrangement.spacedBy(8.dp)) { listOf(1,3,5,10).forEach { Chip("$it min",it==mins) { set(it) } } }; Spacer(Modifier.weight(1f)); Primary("Begin session",begin) } }
@Composable private fun Countdown(exercise: BreathingExercise, done: () -> Unit) { var count by remember { mutableStateOf(3) }; LaunchedEffect(Unit) { repeat(3) { delay(1000); count-- }; done() }; val scale by animateFloatAsState(if(count > 0) 1f else .82f, tween(620, easing = FastOutSlowInEasing), label="countdown_scale"); Box(Modifier.fillMaxSize().background(LumyrinthColor.Background),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Text(exercise.name,color=LumyrinthColor.TextSecondary,fontSize=16.sp);Spacer(Modifier.height(24.dp));Text(if(count>0)count.toString() else "Inhale",color=LumyrinthColor.VioletBright,fontSize=(78*scale).sp,fontWeight=FontWeight.Light);Spacer(Modifier.height(28.dp));Core(if(count>0)(4-count)/4f else 0f,BreathPhase.INHALE,210.dp);Spacer(Modifier.height(24.dp));Text("Get comfortable. Begin gently.",color=LumyrinthColor.TextSecondary)}}
@Composable private fun CustomRhythmScreen(save: (BreathingExercise) -> Unit, back: () -> Unit) = Page { var draft by remember { mutableStateOf(CustomRhythmDraft()) }; Column(Modifier.fillMaxSize(),verticalArrangement=Arrangement.spacedBy(15.dp)) { Text("‹",color=LumyrinthColor.TextPrimary,fontSize=34.sp,modifier=Modifier.clickable { back() }); Text("Your rhythm",color=LumyrinthColor.TextPrimary,fontSize=32.sp); Text("Keep every phase comfortable. Holds are safely limited.",color=LumyrinthColor.TextSecondary); OutlinedTextField(draft.name,{draft=draft.copy(name=it.take(24))},label={Text("Name")},singleLine=true,modifier=Modifier.fillMaxWidth()); listOf("Inhale" to draft.inhaleSeconds,"Hold after inhale" to draft.holdAfterInhaleSeconds,"Exhale" to draft.exhaleSeconds,"Hold after exhale" to draft.holdAfterExhaleSeconds).forEachIndexed { i,(label,value)-> Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.SpaceBetween){Text(label,color=LumyrinthColor.TextPrimary);Row(verticalAlignment=Alignment.CenterVertically){Chip("−"){draft=when(i){0->draft.copy(inhaleSeconds=draft.inhaleSeconds-1);1->draft.copy(holdAfterInhaleSeconds=draft.holdAfterInhaleSeconds-1);2->draft.copy(exhaleSeconds=draft.exhaleSeconds-1);else->draft.copy(holdAfterExhaleSeconds=draft.holdAfterExhaleSeconds-1)}};Text("${value.coerceIn(if(i==1||i==3)0 else 2,if(i==1||i==3)4 else 8)}s",color=LumyrinthColor.VioletBright,modifier=Modifier.width(36.dp),textAlign=TextAlign.Center);Chip("+"){draft=when(i){0->draft.copy(inhaleSeconds=draft.inhaleSeconds+1);1->draft.copy(holdAfterInhaleSeconds=draft.holdAfterInhaleSeconds+1);2->draft.copy(exhaleSeconds=draft.exhaleSeconds+1);else->draft.copy(holdAfterExhaleSeconds=draft.holdAfterExhaleSeconds+1)}}} } }; Spacer(Modifier.weight(1f)); Primary("Save rhythm") { save(draft.asExercise()) } } }
@Composable private fun Session(e:BreathingExercise, mins:Int, done:(Long,Int)->Unit, exit:()->Unit) { val context=LocalContext.current; var mark by remember { mutableLongStateOf(SystemClock.elapsedRealtime()) }; var held by remember { mutableLongStateOf(0) }; var pause by remember { mutableStateOf(false) }; var haptics by remember { mutableStateOf(true) }; var sound by remember { mutableStateOf(true) }; var now by remember { mutableLongStateOf(mark) }; val guide=remember { HapticGuide(context) }; val sounds=remember { GuidanceSoundController(context) }; val ambient=remember { AmbientAudioController(context) }; val prefs by remember{UserPreferencesRepository(context)}.preferences.collectAsState(initial=null); DisposableEffect(Unit){onDispose{sounds.release();ambient.release()}}; LaunchedEffect(pause,prefs?.ambientSound) { if(pause)ambient.pause() else ambient.play(prefs?.ambientSound?:"None") }; LaunchedEffect(pause) { while(!pause){now=SystemClock.elapsedRealtime();delay(32)} }; val elapsed=if(pause) held else held+now-mark; val s=sessionSnapshot(e.pattern,mins*60000L,elapsed); LaunchedEffect(s.phase,s.cyclesCompleted,pause) { if(!pause&&haptics) guide.cue(s.phase); if(!pause&&sound)sounds.cue(s.phase) }; LaunchedEffect(s.isFinishingCycle,s.phaseProgress) { if(s.isFinishingCycle&&s.phase==BreathPhase.EXHALE&&s.phaseProgress>.98){if(haptics)guide.complete();if(sound)sounds.complete();done(elapsed,s.cyclesCompleted)} }; Box(Modifier.fillMaxSize().background(LumyrinthColor.Background).padding(24.dp)) { Column(Modifier.fillMaxSize(),horizontalAlignment=Alignment.CenterHorizontally) { Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween) { Text("×",color=LumyrinthColor.TextSecondary,fontSize=30.sp,modifier=Modifier.clickable{exit()});Text(e.name,color=LumyrinthColor.TextSecondary) }; Spacer(Modifier.weight(1f));Text(if(pause)"PAUSED" else s.phase.label.uppercase(),color=LumyrinthColor.TextPrimary,fontSize=26.sp);Text("${s.phaseRemainingSeconds}",color=LumyrinthColor.VioletBright,fontSize=52.sp);Core(s.phaseProgress,s.phase,260.dp);Text(if(s.isFinishingCycle)"Finishing cycle…" else "%d:%02d remaining".format(s.targetRemainingMillis/60000,(s.targetRemainingMillis/1000)%60),color=LumyrinthColor.TextSecondary);Spacer(Modifier.weight(1f));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){ Chip(if(sound)"Sound on" else "Sound off",sound){sound=!sound};Chip(if(haptics)"Haptic on" else "Haptic off",haptics) { haptics=!haptics };Chip(if(pause)"Resume" else "Pause",true) { if(pause){mark=SystemClock.elapsedRealtime();pause=false}else{held=elapsed;pause=true} } } } } }
@Composable private fun Complete(e:BreathingExercise,mins:Int,done:()->Unit,repeat:()->Unit)=Page { Column(Modifier.fillMaxSize(),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center) { Text("✓",color=LumyrinthColor.VioletBright,fontSize=72.sp);Text("Complete",color=LumyrinthColor.TextPrimary,fontSize=32.sp);Text("$mins min · ${mins*6} cycles",color=LumyrinthColor.TextSecondary);Spacer(Modifier.height(30.dp));Text("How do you feel?",color=LumyrinthColor.TextPrimary);Spacer(Modifier.height(12.dp));Row(horizontalArrangement=Arrangement.spacedBy(7.dp)){listOf("Better","Same","Not great").forEach{Chip(it){}}};Spacer(Modifier.height(32.dp));Primary("Done",done);Spacer(Modifier.height(10.dp));OutlinedButton(repeat,Modifier.fillMaxWidth()){Text("Repeat",color=LumyrinthColor.VioletBright)} } }
@Composable private fun Bottom(current:Screen,go:(Screen)->Unit)=Row(Modifier.fillMaxWidth().background(LumyrinthColor.BackgroundElevated).padding(10.dp).wrapContentSize(Alignment.BottomCenter),horizontalArrangement=Arrangement.SpaceAround){listOf("Home" to Screen.HOME,"Explore" to Screen.EXPLORE,"Progress" to Screen.PROGRESS,"Settings" to Screen.SETTINGS).forEach{(t,s)->Text(t,color=if(s==current)LumyrinthColor.VioletBright else LumyrinthColor.TextTertiary,modifier=Modifier.clickable{go(s)}.padding(7.dp),fontSize=12.sp)}}
@Composable private fun Hero(click:()->Unit)=Card(Modifier.fillMaxWidth().clickable{click()},colors=CardDefaults.cardColors(containerColor=Color.Transparent),shape=RoundedCornerShape(28.dp)){Column(Modifier.background(Brush.linearGradient(listOf(Color(0xFF4A155F),Color(0xFF251030),Color(0xFF35102B)))).padding(22.dp)){Text("Quick breathe",color=LumyrinthColor.TextSecondary);Spacer(Modifier.height(16.dp));Text("Slow Down",color=LumyrinthColor.TextPrimary,fontSize=28.sp);Text("4 inhale · 6 exhale · 3 min",color=LumyrinthColor.TextSecondary);Spacer(Modifier.height(16.dp));Text("Start  →",color=LumyrinthColor.VioletBright,fontWeight=FontWeight.SemiBold)}}
@Composable private fun CardRow(a:String,b:String,c:String,click:()->Unit)=Card(Modifier.fillMaxWidth().clickable{click()},colors=CardDefaults.cardColors(containerColor=LumyrinthColor.Surface),shape=RoundedCornerShape(20.dp)){Row(Modifier.padding(18.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(a,color=LumyrinthColor.TextPrimary,fontSize=17.sp);Text(b,color=LumyrinthColor.TextSecondary,fontSize=13.sp)};Text(c,color=LumyrinthColor.VioletBright,fontSize=13.sp)}}
@Composable private fun SettingToggle(title:String,subtitle:String,checked:Boolean,change:(Boolean)->Unit)=Card(colors=CardDefaults.cardColors(containerColor=LumyrinthColor.Surface),shape=RoundedCornerShape(20.dp)){Row(Modifier.fillMaxWidth().padding(17.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(title,color=LumyrinthColor.TextPrimary,fontSize=17.sp);Text(subtitle,color=LumyrinthColor.TextSecondary,fontSize=13.sp)};Switch(checked,change,colors=SwitchDefaults.colors(checkedThumbColor=LumyrinthColor.TextPrimary,checkedTrackColor=LumyrinthColor.Violet))}}
@Composable private fun Core(p:Float,phase:BreathPhase,size:androidx.compose.ui.unit.Dp){val breathing=when(phase){BreathPhase.INHALE->.78f+.22f*p;BreathPhase.EXHALE->1f-.22f*p;else->1f};val loop=rememberInfiniteTransition(label="core_pulse");val pulse by loop.animateFloat(1f,1.045f,infiniteRepeatable(tween(1050,easing=FastOutSlowInEasing),RepeatMode.Reverse),label="hold_pulse");val q=breathing*if(phase==BreathPhase.HOLD_AFTER_INHALE||phase==BreathPhase.HOLD_AFTER_EXHALE)pulse else 1f;Canvas(Modifier.size(size)){val r=min(this.size.width,this.size.height)*.38f*q;repeat(6){i->drawCircle(LumyrinthColor.VioletBright.copy(alpha=.5f-i*.06f),r+i*12,center,style=Stroke(2f))};drawCircle(LumyrinthColor.Magenta,r*.12f,center)}}
@Composable private fun Chip(t:String,on:Boolean=false,click:()->Unit)=Text(t,color=if(on)LumyrinthColor.TextPrimary else LumyrinthColor.TextSecondary,modifier=Modifier.clip(RoundedCornerShape(18.dp)).background(if(on)LumyrinthColor.Violet else LumyrinthColor.SurfaceSoft).clickable{click()}.padding(12.dp,8.dp),fontSize=13.sp)
@Composable private fun Stat(a:String,b:String)=Card(colors=CardDefaults.cardColors(containerColor=LumyrinthColor.Surface),shape=RoundedCornerShape(16.dp)){Column(Modifier.padding(13.dp)){Text(a,color=LumyrinthColor.VioletBright,fontSize=24.sp);Text(b,color=LumyrinthColor.TextSecondary,fontSize=11.sp)}}
@Composable private fun Label(t:String)=Text(t,color=LumyrinthColor.TextPrimary,fontSize=17.sp,fontWeight=FontWeight.Medium)
@Composable private fun Primary(t:String,click:()->Unit)=Button(click,Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(containerColor=LumyrinthColor.Violet),shape=RoundedCornerShape(18.dp)){Text(t,modifier=Modifier.padding(5.dp))}
